//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.17929
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_AsyncClient.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MathResult", Namespace="http://schemas.datacontract.org/2004/07/WCF_MyServerDatContract")]
    [System.SerializableAttribute()]
    public partial class MathResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double divField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double multField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double subtrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double sumField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double div {
            get {
                return this.divField;
            }
            set {
                if ((this.divField.Equals(value) != true)) {
                    this.divField = value;
                    this.RaisePropertyChanged("div");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double mult {
            get {
                return this.multField;
            }
            set {
                if ((this.multField.Equals(value) != true)) {
                    this.multField = value;
                    this.RaisePropertyChanged("mult");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double subtr {
            get {
                return this.subtrField;
            }
            set {
                if ((this.subtrField.Equals(value) != true)) {
                    this.subtrField = value;
                    this.RaisePropertyChanged("subtr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double sum {
            get {
                return this.sumField;
            }
            set {
                if ((this.sumField.Equals(value) != true)) {
                    this.sumField = value;
                    this.RaisePropertyChanged("sum");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IMyMath")]
    public interface IMyMath {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyMath/Total", ReplyAction="http://tempuri.org/IMyMath/TotalResponse")]
        WCF_AsyncClient.ServiceReference1.MathResult Total(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IMyMath/Total", ReplyAction="http://tempuri.org/IMyMath/TotalResponse")]
        System.IAsyncResult BeginTotal(int x, int y, System.AsyncCallback callback, object asyncState);
        
        WCF_AsyncClient.ServiceReference1.MathResult EndTotal(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMyMathChannel : WCF_AsyncClient.ServiceReference1.IMyMath, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TotalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public TotalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public WCF_AsyncClient.ServiceReference1.MathResult Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((WCF_AsyncClient.ServiceReference1.MathResult)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MyMathClient : System.ServiceModel.ClientBase<WCF_AsyncClient.ServiceReference1.IMyMath>, WCF_AsyncClient.ServiceReference1.IMyMath {
        
        private BeginOperationDelegate onBeginTotalDelegate;
        
        private EndOperationDelegate onEndTotalDelegate;
        
        private System.Threading.SendOrPostCallback onTotalCompletedDelegate;
        
        public MyMathClient() {
        }
        
        public MyMathClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MyMathClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyMathClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyMathClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<TotalCompletedEventArgs> TotalCompleted;
        
        public WCF_AsyncClient.ServiceReference1.MathResult Total(int x, int y) {
            return base.Channel.Total(x, y);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginTotal(int x, int y, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginTotal(x, y, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public WCF_AsyncClient.ServiceReference1.MathResult EndTotal(System.IAsyncResult result) {
            return base.Channel.EndTotal(result);
        }
        
        private System.IAsyncResult OnBeginTotal(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int x = ((int)(inValues[0]));
            int y = ((int)(inValues[1]));
            return this.BeginTotal(x, y, callback, asyncState);
        }
        
        private object[] OnEndTotal(System.IAsyncResult result) {
            WCF_AsyncClient.ServiceReference1.MathResult retVal = this.EndTotal(result);
            return new object[] {
                    retVal};
        }
        
        private void OnTotalCompleted(object state) {
            if ((this.TotalCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.TotalCompleted(this, new TotalCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void TotalAsync(int x, int y) {
            this.TotalAsync(x, y, null);
        }
        
        public void TotalAsync(int x, int y, object userState) {
            if ((this.onBeginTotalDelegate == null)) {
                this.onBeginTotalDelegate = new BeginOperationDelegate(this.OnBeginTotal);
            }
            if ((this.onEndTotalDelegate == null)) {
                this.onEndTotalDelegate = new EndOperationDelegate(this.OnEndTotal);
            }
            if ((this.onTotalCompletedDelegate == null)) {
                this.onTotalCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnTotalCompleted);
            }
            base.InvokeAsync(this.onBeginTotalDelegate, new object[] {
                        x,
                        y}, this.onEndTotalDelegate, this.onTotalCompletedDelegate, userState);
        }
    }
}
