//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Example1DataBaseFirst
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    // Контекст базы данных PhoneStore
    public partial class PhoneStoreEntities : DbContext
    {
        public PhoneStoreEntities()
            : base("name=PhoneStoreEntities")  //PhoneStoreEntities - строка подключения, 
                                               // находится в App.config
        { 
        }
        
        // список таблиц из базы данных
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<UsersInfo> UsersInfo { get; set; }
    }
}
