//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Example1DataBaseFirst
{
    using System;
    using System.Collections.Generic;

    // Сущность (класс). представаляющий запись  таблицы Users
    // базы данных PhoneStore
    public partial class Users
    {
        public Users()
        {
            this.UsersInfo = new HashSet<UsersInfo>();
        }
    
        public long Id { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
    
        public virtual ICollection<UsersInfo> UsersInfo { get; set; }
    }
}
